name: Evidence Gate
on:
  pull_request: { branches: [ main, develop ] }
  workflow_dispatch: {}
permissions: { contents: read }
concurrency: { group: evidence-gate-${{ github.ref }}, cancel-in-progress: true }
jobs:
  verify-evidence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq
      - name: Check required evidence files
        run: |
          required=(
            artifacts/health/verification/CLAIMS.json
            artifacts/health/verification/REPO_STATS.json
            artifacts/health/verification/REPO_STATS.md
            artifacts/health/verification/VERIFICATION_REPORT.md
            artifacts/health/verification/PERF_BUDGET_RESULTS.md
            artifacts/health/verification/SHORTLIST_SLA_RESULTS.md
            artifacts/health/verification/HASHES.txt
          )
          for f in "${required[@]}"; do
            [ -f "$f" ] || { echo "::error ::Missing $f"; exit 1; }
          done
      - name: Require PASS verdict
        run: |
          grep -q "ALL CLAIMS: PASS" artifacts/health/verification/VERIFICATION_REPORT.md \
            || { echo "::error ::Verification report not PASS"; exit 1; }
 
